import { Protocol } from '@/types';

export const PROTOCOLS: Protocol[] = [
  {
    id: 'max-short',
    name: 'Suspensions Max Courtes',
    family: 'force',
    energySystem: 'alactic',
    icon: '⚡',
    summary: '5-12s suspendu · 2-3min repos · 3-5 répét · force pure',
    defaults: {
      hangDuration: 10,
      restBetweenReps: 150,
      reps: 4,
      sets: 3,
      restBetweenSets: 180,
    },
    loadAdvice: 'Dosez pour lâcher entre 5 et 12 secondes. Si vous tenez plus longtemps, ajoutez du poids.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h avant la prochaine séance de force.',
    frequencyAdvice: '1 à 2 fois par semaine, jamais fatigué.',
  },
  {
    id: 'max-long',
    name: 'Suspensions Max Longues',
    family: 'force',
    energySystem: 'alactic',
    icon: '💪',
    summary: '20s suspendu · 3-5min repos · 3-5 répét · hypertrophie',
    defaults: {
      hangDuration: 20,
      restBetweenReps: 240,
      reps: 4,
      sets: 3,
      restBetweenSets: 300,
    },
    loadAdvice: 'Dosez pour lâcher à 20 secondes maximum. Gains lents mais durables.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h avant la prochaine séance de force.',
    frequencyAdvice: '1 à 2 fois par semaine, jamais fatigué.',
  },
  {
    id: 'tendons',
    name: 'Suspensions pour les tendons',
    family: 'force',
    energySystem: 'alactic',
    icon: '🦴',
    summary: '30-45s suspendu · 5min repos · 3 répét · entretien tendons',
    defaults: {
      hangDuration: 40,
      restBetweenReps: 300,
      reps: 3,
      sets: 3,
      restBetweenSets: 300,
    },
    loadAdvice: 'Dosez pour lâcher à environ 45 secondes. Maximum 3 séries en tout (1 par préhension).',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h avant la prochaine séance de force.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'intermittent',
    name: 'Suspensions Intermittentes',
    family: 'force',
    energySystem: 'alactic',
    icon: '🔄',
    summary: '7s/3s × 6 = 1min · 5min repos · force/résistance',
    defaults: {
      hangDuration: 7,
      restBetweenReps: 3,
      reps: 6,
      sets: 2,
      restBetweenSets: 300,
    },
    loadAdvice: 'Confortable sur la réglette choisie. Le risque de blessure est faible.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'continuity-long',
    name: 'Continuité Longue sur poutre',
    family: 'continuity',
    energySystem: 'aerobic',
    icon: '🌊',
    summary: '7s/3s × 6 · 10 séries · 3 tours · endurance aérobie',
    defaults: {
      hangDuration: 7,
      restBetweenReps: 3,
      reps: 6,
      sets: 10,
      restBetweenSets: 60,
      rounds: 3,
      restBetweenRounds: 600,
    },
    loadAdvice: "Délestez avec une poulie à 30-40% de votre max. Vous devez être légèrement fatigué, pas à bout.",
    recoveryAdvice: "Compatible avec le reste de l'entraînement. Peut être casé après une séance de grimpe, jamais avant une séance de force.",
    frequencyAdvice: '2 séances/semaine pendant minimum 8 semaines, maximum 16 semaines.',
  },
  {
    id: 'continuity-short',
    name: 'Continuité Courte sur poutre',
    family: 'continuity',
    energySystem: 'lactic',
    icon: '🔥',
    summary: '7s/3s × 6 · 6 séries · repos 3min · anaérobie lactique',
    defaults: {
      hangDuration: 7,
      restBetweenReps: 3,
      reps: 6,
      sets: 6,
      restBetweenSets: 180,
    },
    loadAdvice: '70-80% de votre max. Vous devez tomber sur les 2 dernières séries des 2 derniers tours.',
    recoveryAdvice: 'Prévoyez un jour de repos le lendemain.',
    frequencyAdvice: '2×/semaine si priorité continuité, 1×/semaine si combiné avec force. Minimum 6 semaines.',
  },
  {
    id: 'weighted-pullups',
    name: 'Tractions Lestées',
    family: 'pullups',
    energySystem: 'alactic',
    icon: '🏋️',
    summary: '5 répét max · 5 séries · 2min repos · force bras',
    defaults: {
      hangDuration: 4,
      restBetweenReps: 3,
      reps: 5,
      sets: 5,
      restBetweenSets: 120,
    },
    loadAdvice: 'Maximum 5 répétitions. Redescendez toujours lentement et sans à-coups.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'negative-pullups',
    name: 'Tractions Négatives',
    family: 'pullups',
    energySystem: 'alactic',
    icon: '⬇️',
    summary: '8s descente · 5 séries · 3min repos · force excentrique',
    defaults: {
      hangDuration: 8,
      restBetweenReps: 0,
      reps: 1,
      sets: 5,
      restBetweenSets: 180,
    },
    loadAdvice: 'Depuis menton au-dessus de la barre, descente en 8 secondes à tension maximale. Option 1 ou 2 bras.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'minute-pullups',
    name: 'Traction Minute',
    family: 'pullups',
    energySystem: 'aerobic',
    icon: '⏱️',
    summary: 'X tractions/minute · 10 minutes · entretien bras',
    defaults: {
      hangDuration: 3,
      restBetweenReps: 2,
      reps: 5,
      sets: 10,
      restBetweenSets: 60,
    },
    loadAdvice: "X tractions au début de chaque minute, repos jusqu'à la fin de la minute. Ajoutez des pompes si la forme le permet.",
    recoveryAdvice: "Séance légère, peut être intégrée à n'importe quel jour.",
    frequencyAdvice: '2 à 3 fois par semaine.',
  },
];

export const getProtocolById = (id: string): Protocol | undefined =>
  PROTOCOLS.find((p) => p.id === id);

export const getProtocolsByFamily = (family: Protocol['family']): Protocol[] =>
  PROTOCOLS.filter((p) => p.family === family);
