import { Protocol } from '@/types';

export const PROTOCOLS: Protocol[] = [
  {
    id: 'max-short',
    name: 'Suspensions Max Courtes',
    family: 'force',
    energySystem: 'alactic',
    icon: '⚡',
    summary: '5-12s suspendu · 2-3min repos · 3-5 répét · force pure',
    description: "Développe la force maximale par adaptations neuromusculaires rapides. Les gains sont les plus rapides de tous les protocoles, mais nécessitent d'être frais et reposé.",
    difficulty: 'intermediate',
    progressionTips: [
      "Ajoutez du poids (1-2 kg à la fois)",
      "Passez à des prises plus petites",
      "Réduisez le nombre de doigts",
      "Visez un seul bras comme objectif ultime",
    ],
    targetedQualities: ["Force maximale doigts", "Recrutement neuromusculaire"],
    defaults: {
      prepDuration: 5,
      hangDuration: 10,
      restBetweenReps: 150,
      reps: 4,
      sets: 3,
      loadKg: 0,
      restBetweenSets: 180,
    },
    loadAdvice: 'Dosez pour lâcher entre 5 et 12 secondes. Si vous tenez plus longtemps, ajoutez du poids.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h avant la prochaine séance de force.',
    frequencyAdvice: '1 à 2 fois par semaine, jamais fatigué.',
  },
  {
    id: 'max-long',
    name: 'Suspensions Max Longues',
    family: 'force',
    energySystem: 'alactic',
    icon: '💪',
    summary: '20s suspendu · 3-5min repos · 3-5 répét · hypertrophie',
    description: "Provoque l'hypertrophie des muscles de l'avant-bras. Processus lent mais gains plus durables que les suspensions courtes. Augmente la taille des muscles fléchisseurs.",
    difficulty: 'intermediate',
    progressionTips: [
      "Ajoutez du poids progressivement",
      "Utilisez des prises plus petites",
      "Augmentez le nombre de répétitions par préhension",
      "Travaillez un seul bras",
    ],
    targetedQualities: ["Hypertrophie avant-bras", "Force de contact"],
    defaults: {
      prepDuration: 5,
      hangDuration: 20,
      restBetweenReps: 240,
      reps: 4,
      sets: 3,
      loadKg: 0,
      restBetweenSets: 300,
    },
    loadAdvice: 'Dosez pour lâcher à 20 secondes maximum. Gains lents mais durables.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h avant la prochaine séance de force.',
    frequencyAdvice: '1 à 2 fois par semaine, jamais fatigué.',
  },
  {
    id: 'tendons',
    name: 'Suspensions pour les tendons',
    family: 'force',
    energySystem: 'alactic',
    icon: '🦴',
    summary: '30-45s suspendu · 5min repos · 3 répét · entretien tendons',
    description: "Rigidifie les tendons et améliore la force de contact. Réduit le jeu dans les doigts pour une saisie plus rapide et plus ferme. Essentiel pour l'entretien des tissus conjonctifs.",
    difficulty: 'advanced',
    progressionTips: [
      "Ajoutez du poids très progressivement",
      "Passez à des prises plus petites",
      "Maximum 3 séries en tout par séance (1 par préhension)",
    ],
    targetedQualities: ["Santé tendons", "Force de contact", "Rigidité articulaire"],
    defaults: {
      prepDuration: 5,
      hangDuration: 40,
      restBetweenReps: 300,
      reps: 3,
      sets: 3,
      loadKg: 0,
      restBetweenSets: 300,
    },
    loadAdvice: 'Dosez pour lâcher à environ 45 secondes. Maximum 3 séries en tout (1 par préhension).',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h avant la prochaine séance de force.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'intermittent',
    name: 'Suspensions Intermittentes',
    family: 'force',
    energySystem: 'alactic',
    icon: '🔄',
    summary: '7s/3s × 6 = 1min · 5min repos · force/résistance',
    description: "Protocole polyvalent à faible risque de blessure. Enchaîne suspension et repos courts pour travailler force et résistance. Idéal tout au long de l'année.",
    difficulty: 'beginner',
    progressionTips: [
      "Allongez la suspension (ex: 8s) ou raccourcissez le repos (ex: 2s)",
      "Ajoutez du poids",
      "Augmentez le nombre de séries",
      "Utilisez des prises plus petites",
    ],
    targetedQualities: ["Force-endurance doigts", "Résistance anaérobie"],
    defaults: {
      prepDuration: 5,
      hangDuration: 7,
      restBetweenReps: 3,
      reps: 6,
      sets: 2,
      loadKg: 0,
      restBetweenSets: 300,
    },
    loadAdvice: 'Confortable sur la réglette choisie. Le risque de blessure est faible.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'continuity-long',
    name: 'Continuité Longue sur poutre',
    family: 'continuity',
    energySystem: 'aerobic',
    icon: '🌊',
    summary: '7s/3s × 6 · 10 séries · 3 tours · endurance aérobie',
    description: "Développe l'endurance aérobie des avant-bras en augmentant la vascularisation. Grimper longtemps à faible intensité. Gains lents (8+ semaines) mais fondamentaux.",
    difficulty: 'beginner',
    progressionTips: [
      "Réduisez le délestage progressivement",
      "Maintenez le programme minimum 8 semaines",
      "2 heures par semaine de volume total recommandé",
      "Placez après la grimpe, jamais avant une séance force",
    ],
    targetedQualities: ["Endurance aérobie", "Vascularisation avant-bras", "Récupération active"],
    defaults: {
      prepDuration: 5,
      hangDuration: 7,
      restBetweenReps: 3,
      reps: 6,
      sets: 10,
      loadKg: 0,
      restBetweenSets: 60,
      rounds: 3,
      restBetweenRounds: 600,
    },
    loadAdvice: "Délestez avec une poulie à 30-40% de votre max. Vous devez être légèrement fatigué, pas à bout.",
    recoveryAdvice: "Compatible avec le reste de l'entraînement. Peut être casé après une séance de grimpe, jamais avant une séance de force.",
    frequencyAdvice: '2 séances/semaine pendant minimum 8 semaines, maximum 16 semaines.',
  },
  {
    id: 'continuity-short',
    name: 'Continuité Courte sur poutre',
    family: 'continuity',
    energySystem: 'lactic',
    icon: '🔥',
    summary: '7s/3s × 6 · 6 séries · repos 3min · anaérobie lactique',
    description: "Travaille le système anaérobie lactique — la capacité à enchaîner des mouvements intenses. Vous devez batailler en fin de séance et chuter sur les dernières séries.",
    difficulty: 'intermediate',
    progressionTips: [
      "Réduisez le délestage ou ajoutez du poids",
      "Programme minimum 6 semaines pour voir des résultats",
      "Prévoir 1 jour repos après la séance",
      "Si combiné avec force : 1×/semaine au lieu de 2",
    ],
    targetedQualities: ["Continuité courte", "Tolérance lactique", "Puissance-endurance"],
    defaults: {
      prepDuration: 5,
      hangDuration: 7,
      restBetweenReps: 3,
      reps: 6,
      sets: 6,
      loadKg: 0,
      restBetweenSets: 180,
    },
    loadAdvice: '70-80% de votre max. Vous devez tomber sur les 2 dernières séries des 2 derniers tours.',
    recoveryAdvice: 'Prévoyez un jour de repos le lendemain.',
    frequencyAdvice: '2×/semaine si priorité continuité, 1×/semaine si combiné avec force. Minimum 6 semaines.',
  },
  {
    id: 'weighted-pullups',
    name: 'Tractions Lestées',
    family: 'pullups',
    energySystem: 'alactic',
    icon: '🏋️',
    summary: '5 répét max · 5 séries · 2min repos · force bras',
    description: "Renforce la chaîne de traction : bras, épaules et dos. Indispensable pour passer d'une prise à l'autre. Descendez toujours lentement et sans à-coups.",
    difficulty: 'intermediate',
    progressionTips: [
      "Ajoutez du poids à chaque séance si possible",
      "Contrôlez la descente (phase excentrique lente)",
      "Variez les prises (barre, poutre, anneaux)",
    ],
    targetedQualities: ["Force de traction", "Force bras/épaules/dos"],
    defaults: {
      prepDuration: 5,
      hangDuration: 4,
      restBetweenReps: 3,
      reps: 5,
      sets: 5,
      loadKg: 0,
      restBetweenSets: 120,
    },
    loadAdvice: 'Maximum 5 répétitions. Redescendez toujours lentement et sans à-coups.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'negative-pullups',
    name: 'Tractions Négatives',
    family: 'pullups',
    energySystem: 'alactic',
    icon: '⬇️',
    summary: '8s descente · 5 séries · 3min repos · force excentrique',
    description: "Travaille la force excentrique en contrôlant la descente depuis menton au-dessus de la barre. Moins risqué qu'une traction standard, excellent pour progresser en force.",
    difficulty: 'beginner',
    progressionTips: [
      "Dosez le poids pour une descente exactement en 8 secondes",
      "Passez à un seul bras quand 2 bras devient facile",
      "Augmentez la charge progressivement",
    ],
    targetedQualities: ["Force excentrique", "Contrôle traction"],
    defaults: {
      prepDuration: 5,
      hangDuration: 8,
      restBetweenReps: 0,
      reps: 1,
      sets: 5,
      loadKg: 0,
      restBetweenSets: 180,
    },
    loadAdvice: 'Depuis menton au-dessus de la barre, descente en 8 secondes à tension maximale. Option 1 ou 2 bras.',
    recoveryAdvice: 'Travaillez la force uniquement quand vous êtes frais. Prévoyez au moins 48h.',
    frequencyAdvice: '1 à 2 fois par semaine.',
  },
  {
    id: 'minute-pullups',
    name: 'Traction Minute',
    family: 'pullups',
    energySystem: 'aerobic',
    icon: '⏱️',
    summary: 'X tractions/minute · 10 minutes · entretien bras',
    description: "Entretien léger de la force de traction. X tractions au début de chaque minute, repos le reste du temps. Peut se combiner avec des pompes.",
    difficulty: 'beginner',
    progressionTips: [
      "Augmentez le nombre de tractions par minute",
      "Ajoutez des pompes dans le temps restant",
      "Augmentez la durée totale (12-15 minutes)",
    ],
    targetedQualities: ["Entretien force traction", "Endurance bras"],
    defaults: {
      prepDuration: 5,
      hangDuration: 3,
      restBetweenReps: 2,
      reps: 5,
      sets: 10,
      loadKg: 0,
      restBetweenSets: 60,
    },
    loadAdvice: "X tractions au début de chaque minute, repos jusqu'à la fin de la minute. Ajoutez des pompes si la forme le permet.",
    recoveryAdvice: "Séance légère, peut être intégrée à n'importe quel jour.",
    frequencyAdvice: '2 à 3 fois par semaine.',
  },
];

export const getProtocolById = (id: string): Protocol | undefined =>
  PROTOCOLS.find((p) => p.id === id);

export const getProtocolsByFamily = (family: Protocol['family']): Protocol[] =>
  PROTOCOLS.filter((p) => p.family === family);
